export const Actions = {
  Themes: {
    SET_THEME: "SET_THEME"
  },
  Languages: {
    SET_LANGUAGE: "SET_LANGUAGE"
  },
  Room: {
    SET_ROOM_DATA: "SET_ROOM_DATA",
    SET_ROOM_USERS: "SET_ROOM_USERS",
    UPDATE_USER_CURSOR_COORDINATES: "UPDATE_USER_CURSOR_COORDINATES",
    ADD_USER_TO_ROOM: "ADD_USER_TO_ROOM",
    REMOVE_USER_FROM_ROOM: "REMOVE_USER_FROM_ROOM"
  },
  User: {
    SET_USER: "SET_USER",
    SET_USER_ID: "SET_USER_ID",
    SET_USER_ROOM_INFO: "SET_USER_ROOM_INFO",
    SET_USER_NAME: "SET_USER_NAME"
  },
  Execution: {
    SET_LIVE_EXECUTION: "SET_LIVE_EXECUTION"
  },
  Code: {
    SET_CODE: "SET_CODE"
  }
};
